#!/bin/sh
case $1/$2 in
  pre/*)
    echo "Going to $2..."
    # Place your pre suspend commands here, or `exit 0` if no pre suspend action required
    /home/abszolut/app/speaker_switch/speaker_off.sh
    ;;
  post/*)
    echo "Waking up from $2..."
    # Place your post suspend (resume) commands here, or `exit 0` if no post suspend action required
    /home/abszolut/app/speaker_switch/speaker_on.sh
    ;;
esac
